site_name: IBM App Modernization POC
site_author: Alejandro Palumbo
repo_url: https://github.com/Client-Engineering-US-West/Application-Development.git

theme:
  name: material

nav:
  - Home: index.md
  - Workstation Setup: workstation-setup.md
  - Demo Environments:
      - Liberty Environment: liberty-demo/index.md
      - WCA Environment: wca4j-demo/index.md
  # Uncomment below when lab files exist:
  # - App Development & Modernization with AMA/TA & WCA:
  #     - Lab 1 - Install AMA/TA: labs/lab1-installmd
  #     - Lab 2 - Scan Applications: labs/lab2-scan.md
  #     - Lab 3 - Explain: labs/lab3-explain.md
  #     - Lab 4 - Modernize: labs/lab4-modernize.md
  #     - Lab 5 - Upgrade Java: labs/lab5-upgrade-java.md
  #     - Lab 6 - Unit Test: labs/lab6-unit-test.md
  #     - Lab 7 - Containerize: labs/lab7-containers.md
  #     - Lab 8 - Deploy to OCP: labs/lab8-deploy.md
